import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css'

import "./globals.css";
import Link from "next/link";
import dynamic from "next/dynamic";

const poppins = Poppins({
  weight:['300','500','900'],
  subsets:['latin']
})


export const metadata: Metadata = {
  title: "J & R - Amor em Código",
  description: "Generated by create next app",
  authors: [{ name: "Victor Kiss", url: "https://github.com/victor-kiss" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const Navbar = dynamic(() => import('@/app/components/navbar/Navbar'));
  const MeshBlob = dynamic(() => import('@/app/components/blob/Blob'));
  return (
    <html lang="pt-br">
      <body
        className={`relative ${poppins.className}  antialiased scroll-smooth bg-black`}
      >
        <MeshBlob/>
        {/* Navbar */}
        <Navbar/>

        {children}

        {/*Footer */}
     <footer className="bg-[rgba(0,0,0,0.4)] text-white p-4 text-center">
  <p className=" text-white mb-2">
    Feito com <i className="bi bi-heart-fill align-middle text-red-500 drop-shadow-sm"></i> por Victor Kiss
  </p>
  <Link
    href="/"
    className="text-sm text-[#FF8C42] transition-colors "
  >
    Voltar ao topo
  </Link>
</footer>


      </body>
    </html>
  );
}
